config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/splash'
  get 'static_pages/profile'

  get 'photos/create'


  # post 'test', to: 'places#test'

  get 'latest', to: 'places#latest'

  post 'tally', to: 'places#tally'
  get 'get/tally',  to: 'places#get_tally'

  resources :tallies



<<<<<<< HEAD
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
=======
  devise_for :users
>>>>>>> bbdd858212d0337f0d5c5fa08e5c0da9c6cd9b82

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

  end

  root 'places#index'
  resources :places do
    resources :comments, :photos, only: :create
    # get '/tally', to: "places#all_tally"
  end
  resources :users do
    patch :avatars, only: :create
  end

  mount ActionCable.server, at: '/cable'
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :picture, PictureUploader

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos
  has_one :tally, dependent: :destroy

  # Google maps API
  geocoded_by :address
  after_validation :geocode

  # Core validations for application
  validates :name, :address, :description, presence: true
  validates :name, length: { in: 3..52 }
  validates :address, length: { in: 9..55 }
  validates :description, length: { in: 20..259 }

  # Scopes available to places controller
  scope :latest, -> { order(created_at: :desc) }
  scope :oldest, -> { order(created_at: :asc) }

  def tally_up
    new_tally = tally.tally_yes += 1
    new_score = tally.score += 1
    percentage = (new_tally.to_f / new_score * 100).to_i
    tally.update_attributes(tally_yes: new_tally, score: new_score,
                            percent: percentage)
  end

  def tally_down
    new_tally = tally.tally_no += 1
    new_score = tally.score += 1
    percentage = (tally.tally_yes.to_f / new_score * 100).to_i
    tally.update_attributes(tally_no: new_tally, score: new_score,
                            percent: percentage)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: %I[new create edit update destroy tally]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
    @user = User.find(current_user.id) if current_user
  end

  def edit
    @place = Place.find(params[:id]).to_i
    return redirect_to @place, status: :forbidden if @place.user != current_user
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @place = Place.find(params[:id])
    return redirect_to @place, status: :forbidden if @place.user != current_user

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    return redirect_to @place, status: :forbidden if @place.user != current_user
    @place.destroy
    redirect_to root_path
  end

  def tally
    @place = Place.find(params[:place_id].to_i)
    if params[:user_response] == 'yes'
      if vote_exist?(@place, current_user.id)
        puts "Aleady Voted!"
      else
        @place.tally_up
        generate_vote(@place, current_user.id)
      end
    elsif params[:user_response] == 'no'
      if vote_exist?(@place, current_user.id)
        puts "Already voted"
      else
        @place.tally_down
        generate_vote(@place, current_user.id)
      end
    end
    broadcast_to_tally(@place)
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description, :range)
  end

  helper_method :generate_vote
  def generate_vote(place, user_id)
    Vote.create!(voter_id: user_id, tally_id: place.tally.id)
  end

  helper_method :vote_exist?
  def vote_exist?(place, user_id)
    place.tally.votes.exists?(voter_id: user_id)
  end

  helper_method :score
  def score(tally_yes, score)
    (tally_yes / score * 100).to_i
  end

  helper_method :dollar_range
  def dollar_range(num)
    ranges = { '1' => '$', '2' => '$$', '3' => '$$$', '4' => '$$$$' }
    ranges[num]
  end

  helper_method :format_date
  def format_date(date)
    formatted = date.strftime('%b %e, %l:%M %p')
    formatted
  end

  helper_method :broadcast_to_tally
  def broadcast_to_tally(place)
    ActionCable.server.broadcast 'tally_channel',
                                 content: place.tally.percent,
                                 place_id: place.id,
                                 score: place.tally.score
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<h1>Edit Your Place</h1>

<div class="booyah-box col-6 offset-3">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<section class='content'>
  <section class="places-items">
    <% @places.each_with_index do |place, index| %>
      <article class="place-item">
        <div class='place-inner'>
          <h3><%= link_to place.name, place_path(place.id) %></h3>
          <div class='score-box'>
            <span>
              <%= render partial: 'shared/score', locals: { place: place } %>
            </span>
            <span class='range'>
              <%= dollar_range(place.range) %>
            </span>
          </div>
          <div class='image-box'>
            <% if place.photos.empty?  %>
              <%= image_tag('placeholder.png', class: 'place-image') %>
              <%= image_tag('placeholder.png', class: 'place-image') %>
              <%= image_tag('placeholder.png', class: 'place-image') %>
              <%= image_tag('placeholder.png', class: 'place-image') %>
            <% else %>
              <% place.photos.each do |photo| %>
                <%= image_tag(photo.picture.url, class: 'place-image') %>
              <% end %>
            <% end %>
          </div>
          <div class='place-description'>
            <%= place.description %>
          </div>
        </div>

        <div class='recommend'>
          <p>
            <%= button_tag image_tag 'thumbs-up.png', class: 'score-btn-yes', data: {'place-id-yes' =>  place.id } %>
          </p>
          <p>
            <%= button_tag image_tag 'thumbs-down.png', class: 'score-btn-no', data: {'place-id-no' => place.id } %>
          </p>
        </div>
      </article>
      <% end %>
  </section>
</section>

app/views/places/index.js.erb
// alert('cpmment go here');

app/views/places/new.html.erb
<div class='content'>
  <div class='search-bar'></div>
  <div class='new-place'>
    <h3>Add New Place</h3>
      <%= simple_form_for @place do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <div class='price-range'>
          <span class='price-text'>Price range: </span>
          <span class='price-range-sym'><%= f.radio_button(:range, "1") %> $</span>
          <span class='price-range-sym'><%= f.radio_button(:range, "2") %> $$</span>
          <span class='price-range-sym'><%= f.radio_button(:range, "3") %> $$$</span>
          <span class='price-range-sym'><%= f.radio_button(:range, "4") %> $$$$</span>
        </div>
        <%= f.input :description %>
        <br />
        <%= f.submit 'Add Place', class: 'add-place-btn btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/places/show.html.erb
  <!-- Places information -->
<div class="place-information">
  <div class='inner-information'>
    <h1 class='place-name'><%= @place.name %></h1>
    <div class='score-box'>
      <span>
        <%= render partial: 'shared/score', locals: { place: @place } %>
      </span>
      <span class='range'>
        <%= dollar_range(@place.range) %>
      </span>
    </div>
    <p class='place-description'>
      <%= @place.description %>
    </p>
    <div>
      <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
        <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
      <% end %>
    </div>
  <!-- Places information -->

  <!-- Places images -->
  <div class='places-images'>
    <div class='share'>
      <h5 class='photo-heading'>Photos from Jake's Dilemma</h5>
      <div class="btn-group add-photo-btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-secondary text-center add-photo" data-toggle="modal" data-target="#myModal"><i class="add fa fa-plus-circle"></i><span class='add-text'>Add</span></button>
      </div>
    </div>
    <div id="film_roll">
    <% @place.photos.each_with_index do |photo, index| %>
      <%= photo.caption %>
      <%= link_to photo.picture.to_s, data: { lightbox: 'image1'} do %>
        <%= image_tag photo.picture.url %>
      <% end %>
    <% end %>
    </div>
  </div>
    <!-- Places images -->
  </div>
</div>

<!-- Comment Section -->
<div class="booyah-box-header comments">
  <button type="button" class="write-review-btn btn btn-secondary text-center" data-toggle="modal" data-target="#reviewModal">
    <i class="add fa fa-plus-circle"></i>
    <span>Leave a comment</span>
  </button>

  <h5 class="review-heading"><%= @place.comments.length %> Comments</h5>

  <div class='clear'></div>

  <div class='row'>
    <% @place.comments.each do |comment| %>
      <div class="lone-review col-10 col-sm-10 offset-1" %>
        <div>
          <div class='review-text'>
            <h6 class='author'>Jeff Taylor</h6>
            <p class='user-comment'><%= comment.message %></p>
            <p class='date'><%= time_ago_in_words(comment.created_at) %> ago</p>
            <br>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<!-- Comment Section -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
            <%= f.input :caption %>
            <%= f.input :picture %>
            <%= f.submit "Add photo", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLongTitle">Write your review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
      <div class="modal-body">
        <div class='form-outter'>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <div class='review-box'>
            <div class="review-input">
            <%= f.input :message, id: "review-text", placeholder: 'Add review...' %>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
            </div>
            <div class="review-submit">
              <%= f.submit "Post", class: 'btn btn-primary review-btn' %>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <!-- Modal -->

  <script>
$(function() {
  fr = new FilmRoll({
    container: '#film_roll',
    height: 330
  });
});
</script>